version: '3'  # версия формата docker-compose файла

services:
  app:  # основной сервис с приложением
    build: .  # сборка образа из Dockerfile в текущей папке
    volumes:  # подключение папки с хоста в контейнер
      - .:/app  # текущая папка проекта -> /app внутри контейнера
    tty: true  # даем контейнеру виртуальный терминал (для работы input())
    stdin_open: true  # разрешение ввода с клавиатуры
    command: bash -c "python W09-T03.py"  # команда запуска приложения
    
