name: Python CI (pytest)

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8 black

      - name: Run pytest tests
        run: |
          python -m pytest W06/ W10/ --verbose

      - name: Run flake8 linter
        run: |
          flake8 W01/ W02/ W03/ W04/ W05/ W06/ W07/ W08/ W09/ W10 --count --show-source --statistics

      - name: Run black formatter
        run: |
          black --check W01/ W02/ W03/ W04/ W05/ W06/ W07/ W08/ W09/ W10 --verbose