name: Python CI (pytest + unittest)

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pytest  

      - name: Run pytest tests
        run: |
          python -m pytest W06/ W10/

      - name: Run unittest tests
        run: |
          python -m unittest discover -s W06/ W10/
